/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_BIT_RATE 8000000

#define DEFAULT_LOCAL_PORT_RANGE_FIRST 27183

#define DEFAULT_LOCAL_PORT_RANGE_LAST 27199

#define HAVE_ASPRINTF

#define HAVE_SOCK_CLOEXEC

#define HAVE_STRDUP

#define HAVE_USB

#define HAVE_V4L2

#define HAVE_VASPRINTF

#undef PORTABLE

#define PREFIX "/usr/local"

#define SCRCPY_VERSION "1.23"

#undef SERVER_DEBUGGER

#define SERVER_DEBUGGER_METHOD_NEW

#define _GNU_SOURCE

#define _POSIX_C_SOURCE 200809L

#define _XOPEN_SOURCE 700

